#68 - Create Routes.jsx and updated links across all components using…
edipoarg/radar pull request #103
Opened 2024-02-19 18:57 UTC by alexaiconejo

Created the Routes.jsx component, placed it within src/components/Routes.jsx; it could be moved to src/routes, as preferred. Replaced links across all components (Analisis, Conecta, Footer, Main2, Marquee, Navbar, Notas, as well as App and Main), and it's working fine.

The issue still pending is that the links to "analisis" and "main2" currently function as anchors with the ids "analisis" and "Main2" within App.jsx using a scroll link. For now, I replaced them as they were, but it would be necessary to modify them to eliminate the ids and make them work similarly within any component, not just within App. The same issue exists with issues 97 and 98; they don't work because they should be scroll links within the same component. When redirecting to the same route, it doesn't return to the beginning of the App.jsx component.

2024-02-19 19:45 UTC, alexaiconejo commented
Updated the ids for "analisis" and "Main2" to "analisisAnchor" and "main2Anchor" respectively in App.jsx, 
   and incorporated them as routes within Routes.jsx. Additionally, introduced the "homeAnchor" route within App.jsx,
   redirecting to the first component for scroll linking with that id. That resolved issues #97 and #98.

2024-02-19 20:24 UTC, alexaiconejo commented
Renamed Routes.jsx to index.js and moved it to src/routes/index.js.
Replaced all imports accordingly.
Exported an object named Navlinks containing all the previous constants.
Replaced the routes from SomeRoute to Navlinks.SomeRoute.

2024-02-19 20:48 UTC, xaiki requested changes
we're already in the NavLinks object,

AnchorRoute makes no sense
EmailRoute either

probably better to remove all "Route" suffixes.

2024-02-20 14:34 UTC, xaiki requested changes
we need to use the consts everywhere for them to make sense.
please check that the router change are actually equivalent.

2024-02-20 14:34 UTC, xaiki commented on src/App.jsx
> +    <div id="homeAnchor" className={styles.App}>
here you want to use the string from NavLinks
DRY: Donot Repeat Yourself

2024-02-20 14:34 UTC, xaiki commented on src/components/Analisis.jsx
> +    <div id="analisisAnchor" className={styles.analisis}>
ditto

2024-02-20 14:34 UTC, xaiki commented on src/components/Main2.jsx
> +    <div id="main2Anchor" className={styles.Main2}>
ditto

2024-02-20 14:34 UTC, xaiki commented on src/components/Navbar.jsx
> +          <Nav.Link as={Link} to={Navlinks.home}>
why did you add as={Link} ?

2024-02-20 14:34 UTC, xaiki commented on src/main.jsx
> +      { path: Navlinks.reporta, element: <Reporta /> },
this will break
Navlinks.reporta links to google docs, not to /reporta

2024-02-20 14:34 UTC, xaiki commented on src/main.jsx
> +      { path: Navlinks.main2, element: <Main2 /> },
this will break,
Navlinks.main2 is main2Anchor not /main2

2024-02-20 14:34 UTC, xaiki commented on src/main.jsx
>      path: "/",
this whole object should probably moved to routes/
but that can be done later.

2024-02-20 16:59 UTC, xaiki approved these changes
lgtm,

this is a fairly large PR
congrats on getting it through.

2024-02-20 16:59 UTC, merged