services: google: guard against bad dates
edipoarg/radar pull request #22
Opened 2024-01-12 19:05 UTC by xaiki

formerlly a typo in dates like '2/10/2/03' would result in a 1902 date and would pass undetected.

we parse dates with a more demanding regex and guard for failures to report bad dates

2024-01-12 19:58 UTC, juanigaray requested changes
Cambios de función no evidente

2024-01-12 19:58 UTC, juanigaray commented on services/google-sheets.js
> +            } else if (event[g].hasOwnProperty("includes") && event[g].includes("")) {
el cambio a hasOwnProperty por qué es?

2024-01-12 19:58 UTC, juanigaray commented on services/google-sheets.js
> +        ;['tipo','tipoId', 'componente', 'componenteId', 'date'].forEach(g => {
la f estaba haciendo shadowing? no entiendo este cambio totalmente. En otro orden de cosas, capaz en lugar de g usaría "eventKey" como nombre descriptivo

2024-01-12 19:58 UTC, juanigaray commented on services/google-sheets.js
> +            } else if (event[g].hasOwnProperty("includes") && event[g].includes("")) {
El caso de que incluya un string vacío qué representa? Capaz una constante nombrada me daría más contexto

2024-01-13 16:52 UTC, xaiki commented on services/google-sheets.js
> +            } else if (event[g].hasOwnProperty("includes") && event[g].includes("")) {
Me pareció más correcto. 
ese chunk no es esencial

2024-01-13 16:52 UTC, xaiki commented on services/google-sheets.js
> +        ;['tipo','tipoId', 'componente', 'componenteId', 'date'].forEach(g => {
Correcto, agreed, no lo voy a poder resolver en estos días

2024-01-13 16:54 UTC, xaiki commented on services/google-sheets.js
> +            } else if (event[g].hasOwnProperty("includes") && event[g].includes("")) {
El test a includes realmente es un súper « instanceof Array » si tiene ‘ ´ es que algo se parseo mal

2024-01-13 20:40 UTC, juanigaray commented on services/google-sheets.js
> +            } else if (event[g].hasOwnProperty("includes") && event[g].includes("")) {
Nit: extraería a isArray() y a eventFieldHasParsedCorrectly() o algo así

2024-01-14 14:24 UTC, xaiki commented on services/google-sheets.js
> +            } else if (event[g].hasOwnProperty("includes") && event[g].includes("")) {
seh, me parece innesesario es 1 linea, de ultima le metemos un comentario, pero me parece que es bastante expresivo para entenderse como esta.

2024-01-14 17:28 UTC, juanigaray approved these changes
Como feedback, este código sería más confiable si tuviera tests con casos bordes como el del bug. Aprobado

2024-01-15 00:01 UTC, merged