#33 - first pop up css fix
edipoarg/radar pull request #46
Opened 2024-01-26 19:51 UTC by alexaiconejo

1. Fix the order of  @media (min-width: 400px) /*celus mas grandes*/ by moving it to line 52. It was causing issues with @media (min-width: 768px) and @media (min-width: 1200px).

https://github.com/edipoarg/radar/blob/d2227556588531f7acc2539ac89f82a237cab22c/src/components/Popup.module.css#L52C1-L70C2

2. Add className={styles.displayFecha} to Popup.jsx and .displayFecha to Popup.module.css. It was deleted during the CSS migration.

https://github.com/edipoarg/radar/blob/d2227556588531f7acc2539ac89f82a237cab22c/src/components/Popup.jsx#L11

https://github.com/edipoarg/radar/blob/d2227556588531f7acc2539ac89f82a237cab22c/src/components/Popup.module.css#L30-L34

2024-01-26 20:16 UTC, alexaiconejo commented
in 'Closes #33 - Fix Popup data, delete displayTipo' I just deleted this line:
    <p className={styles.displayTipo}>{tipo.join(" ")}</p>

En la pagina publicada no estaba el tipo de caso en el display. No sé si eso lo agregaron a propósito.

Por algún motivo falló el build, creo que es algo de Eslint

2024-01-26 20:23 UTC, alexaiconejo commented
Esto resuelve el commit #32 también.

2024-01-27 13:07 UTC, juanigaray commented on src/components/Popup.module.css
>  .displayTipo {
Acá te quedó esto como código muerto!

2024-01-27 13:10 UTC, juanigaray requested changes
Eliminaste el dato `tipo`de `Popup.jsx`, pero en `Markers.jsx`, línea 50, ese dato se sigue insertando en el objeto que se le termina pasando a Popup. Creo que habría que eliminarlo en este PR

2024-01-29 15:47 UTC, alexaiconejo commented
Listo, en el ultimo commit 14c6f243d9028e96c569adff787598d996112e38
eliminé tipo de setPopUpInfo en el componente Markers que fue la última modificación que hicimos porque el pop up no muestra la información del tipo de caso.

2024-01-30 12:16 UTC, juanigaray approved these changes
Piola

2024-01-30 18:40 UTC, merged